### ISSUE TITLE
Last update crushed my shedules

### ISSUE THREAD

**Issue by gribouk** [nielsfaber/scheduler-card#261]
After updating to v2.0.1 yesterday all my shedules now have this:

defective shedule entity: switch....

Any idea what does this suppose to [mean?[](url)](url)

**Comment by nielsfaber** [comment]
Did you try:
- restarting HA afterwards 
- Checking the log for error messages
- Checking the state / attributes of these entities
- Checking the scheduler.storage file in .storage directory 

please share this information, so I can see where it went wrong and make adjustments.
Note that the problem is likely in the scheduler-component.
Are you using V3.0.0?

**Comment by Kalypox** [comment]
Hi,

I have exactly the same problem.
I tried to restart, i checked the .storage/scheduler, all seems good:
```
{
    "version": 1,
    "key": "scheduler.storage",
    "data": {
        "schedules": [
            {
                "schedule_id": "f45c48",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "07:30:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.toilettes_thermostat",
                                "service_data": {
                                    "hvac_mode": "off"
                                }
                            }
                        ]
                    },
                    {
                        "start": "07:30:00",
                        "stop": "20:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.toilettes_thermostat",
                                "service_data": {
                                    "hvac_mode": "heat",
                                    "temperature": 19
                                }
                            }
                        ]
                    },
                    {
                        "start": "20:00:00",
                        "stop": "00:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.toilettes_thermostat",
                                "service_data": {
                                    "hvac_mode": "off"
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "",
                "enabled": true
            }
        ]
    }
}
```
![image](https://user-images.githubusercontent.com/2879180/103090188-989fa900-45f0-11eb-8e4b-8169e1c54853.png)
Log:
```
2020-12-24 13:54:37 INFO (MainThread) [homeassistant.setup] Setting up scheduler
2020-12-24 13:54:37 INFO (MainThread) [homeassistant.setup] Setup of domain scheduler took 0.0 seconds
2020-12-24 13:54:37 INFO (MainThread) [homeassistant.components.switch] Setting up switch.scheduler
2020-12-24 13:58:26 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.scheduler entity: switch.schedule_f45c48
2020-12-24 13:58:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.scheduler entity: switch.schedule_f45c48
```
The entity is good too.
I restarted HA, and my RPi too.
With v3 too

**Comment by Kalypox** [comment]
OK, now (i don't know why), the card are displayed:
![image](https://user-images.githubusercontent.com/2879180/103092120-8294e700-45f6-11eb-8ddc-2d62d2004383.png)


But the scheduler doesn't works:
```
2020-12-24 14:40:26 INFO (MainThread) [homeassistant.components.generic_thermostat.climate] Obtained current and target temperature. Generic thermostat active. 22.47, 19.0
2020-12-24 14:40:26 INFO (MainThread) [homeassistant.components.generic_thermostat.climate] Obtained current and target temperature. Generic thermostat active. 18.06, 21.0
2020-12-24 14:40:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/switch.py", line 708, in async_check_entities_available
await cb_func()
File "/config/custom_components/scheduler/switch.py", line 464, in async_handle_device_available
await self.async_execute_action(service_call, self._queued_entry)
File "/config/custom_components/scheduler/switch.py", line 493, in async_execute_action
current_slot = self.schedule["timeslots"][timeslot]
TypeError: list indices must be integers or slices, not NoneType
2020-12-24 14:40:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/switch.py", line 708, in async_check_entities_available
await cb_func()
File "/config/custom_components/scheduler/switch.py", line 464, in async_handle_device_available
await self.async_execute_action(service_call, self._queued_entry)
File "/config/custom_components/scheduler/switch.py", line 493, in async_execute_action
current_slot = self.schedule["timeslots"][timeslot]
TypeError: list indices must be integers or slices, not NoneType
2020-12-24 14:40:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/switch.py", line 708, in async_check_entities_available
await cb_func()
File "/config/custom_components/scheduler/switch.py", line 464, in async_handle_device_available
await self.async_execute_action(service_call, self._queued_entry)
File "/config/custom_components/scheduler/switch.py", line 493, in async_execute_action
current_slot = self.schedule["timeslots"][timeslot]
TypeError: list indices must be integers or slices, not NoneType
2020-12-24 14:40:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/switch.py", line 708, in async_check_entities_available
await cb_func()
File "/config/custom_components/scheduler/switch.py", line 464, in async_handle_device_available
await self.async_execute_action(service_call, self._queued_entry)
File "/config/custom_components/scheduler/switch.py", line 493, in async_execute_action
current_slot = self.schedule["timeslots"][timeslot]
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by gribouk** [comment]
I am back...

1. I do restart HA every 10 minutes lately since do a lot of coding which needs to hard reboot for testing.
2.  The HA log is empty for messages from Sheduler. Is there any other personal log to look into like addons have?
3. For states and  entities see pic attached. The one at the buttom is turned off and it is displayd in EVERY shedule instatnce now!
![sch-1](https://user-images.githubusercontent.com/72703085/103100587-585a1e00-4624-11eb-8a0c-d1f316b05780.jpg)

4. \\HOMEASSISTANT\config\custom_components\scheduler - there is no such file. What is the path to it?
5.  Yes, it is V.3.0.0
6.  To give you an indication of what it looks like I give you a shot of one of the intefrface pages. If you look into sheduler part, it gives me a message the some schedule is defective. And the names of others shedules are gone as well replaced with their ids or something...
![sch-2](https://user-images.githubusercontent.com/72703085/103100822-855b0080-4625-11eb-9c52-d7f5f08a1b4c.jpg)

**Comment by nielsfaber** [comment]
@gribouk  
```
File "/config/custom_components/scheduler/switch.py", line 323, in calculate_next_timeslot
next_slot = timeslot_order[0]
IndexError: list index out of range
```
This error suggests that  you have created a schedule which has zero timeslots.
Can you verify which entity it is, and look up how you configered it?
Could it be related to this one:
![image](https://user-images.githubusercontent.com/16861605/103102387-fb5a6a00-461b-11eb-989b-e7c219022d70.png)

The yellow block is still clickable, so you can edit / delete it.

**Comment by gribouk** [comment]
No so fast... When I attempted to delete it all of my still working shedules gone to 'defective' state, lost their names and I was never able to retrive those again... So I decided to reinstall whole thing from scratch and nothing worked untill I reinstalled v3.0.0.b. Now I am bussy with getting all my schedules ( and I had ~30 of these ) back...

**Comment by aalbul** [comment]
I'm experiencing the same issue. Basically, no matter what schedule I'm adding, I'm getting a "Defective schedule entity:".
Downgrade to 3.0.0b works. Thanks @gribouk

**Comment by hacker1024** [comment]
I installed 2.0.1 from scratch and this issue is effecting any schedules I make.

**Comment by ldsmovil** [comment]
same issue, defective schedule entity.....

**Comment by ldsmovil** [comment]
working for me....giving a name for the entity.....rare

**Comment by kristomi** [comment]
I had the same issue after upgrading to component 3.0.0, but following @aalbul 's tip and downgrading to 3.0.0b worked for me.

**Comment by giggo** [comment]
...
> Could it be related to this one:
> ![image](https://user-images.githubusercontent.com/16861605/103102387-fb5a6a00-461b-11eb-989b-e7c219022d70.png)
> 
> The yellow block is still clickable, so you can edit / delete it.

I can't click on it to edit or delete it

**Comment by KTibow** [comment]
You can always try to clear your whole storage by opening .storage and deleting the scheduler.storage file. If you’re using Samba, then check “Show hidden files and folders” under View on Windows Explorer to show the .storage folder. If you’re using Configurator, then remove .storage from hidden files/folders in the addon’s config.

**Comment by nielsfaber** [comment]
Could someone who experiences problems share his `scheduler.storage` file content?
I tried reproducing the problem by using the file from https://github.com/nielsfaber/scheduler-card/issues/261#issuecomment-750877029 but for me it shows up fine.
Unfortunately I can only help with this issue once I have a reproduction scenario.

**Comment by Domy5** [comment]
I had the same problem, after installing and configuring several times, delete only the integration (configuration / integration), also delete the file in /ip/config/.storage/scheduler.storage and now if restarting HA I integrated the integration again

and that's how it works

**Comment by dennyreiter** [comment]
I just installed it for the first time today and have not been able to make a schedule.  This is my .storage file:
```
{
    "version": 1,
    "key": "scheduler.storage",
    "data": {
        "schedules": [
            {
                "schedule_id": "097211",
                "timeslots": [
                    {
                        "start": "07:00:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "switch.turn_on",
                                "entity_id": "switch.media_room_christmas_tree_switch",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": null,
                "enabled": true
            }
        ]
    }
}
```
![image](https://user-images.githubusercontent.com/7246759/103180327-685b4300-485a-11eb-8df6-8ddc63fa4502.png)

**Comment by nielsfaber** [comment]
@dennyreiter the storage looks OK, matches with the GUI screenshot.
What does not work?
You get the yellow message block?

**Comment by dennyreiter** [comment]
Well, after another restart, it's now working.  Yes, I was getting the yellow message block, but I just did another restart and it shows up and I was able to add another entry.  No errors in the logs that I saw.

**Comment by nielsfaber** [comment]
Glad you fixed it.
More people seem to be able to fixed the problems by restarting.
This shouldn’t be necessary, but at least it gives a clue. I will try to reinstall it on my HA, see if I can make it show up.
Thanks for sharing

**Comment by dennyreiter** [comment]
Thanks for the great component. I'm excited to put it to use.

**Comment by nielsfaber** [comment]
FYI: I released v3.0.1 of the scheduler-component which should eliminate the "Defective schedule entity" occurring right after installing the integration (it doesn't require a HA restart anymore).
I am not claiming this update will fix all the problems mentioned here... I still have troubles reproducing this issue.

**Comment by giggo** [comment]
Thanks @nielsfaber 
I am still seeing the defective scheedule entities after the 3.0.1 upgrade:
![image](https://user-images.githubusercontent.com/213763/103317516-b07d8f80-4a2b-11eb-8a61-8cc10184c295.png)

Any log files/snippets I can help with?

**Comment by nielsfaber** [comment]
@giggo Please check the following:
* What happens if you click the box? Can you still edit the schedule as normal? Does everything look OK here?
* If you go to developer. tools -> entities and look up this schedule entity, does it have state *unknown*? Could you share a snippet of all the attributes displayed here?
* Could you share the log entries in Configuration -> Logs for custom_component.scheduler?
* In .storage/scheduler.storage, could you copy the JSON configuration for this schedule?

Is this schedule defective since you updated from v2.1.1 (or older) to the new v3.0.x ?
If so, probably something went wrong in the migration, I hope this is visible from the scheduler.storage entry.

**Comment by nielsfaber** [comment]
@gribouk 
The problems are probably caused by failing to migrate the schedules from the old (v2.1.1 or older) version to the new format, causing one or more schedules to be corrupted.
With the recent updates of the scheduler-component and the card these corrupted schedules should be identified and can be removed, allowing to recover from this problem.
Unfortunately I haven't been able to find the cause of the migration leading to corrupted schedules.

Could you update the card and the component, and see if the problems are solved now?

**Comment by gribouk** [comment]
As far as I am concerned, I had to redo all my schedules from scratch under v3.0.0b after all of those failed eventually. So, for the apparent reason, I would not have the information if the new update solves the problem. I would prefer to wait for the other's people response from those with the same problem however, before upgraiding again - you never know what might come out this time, and I would like to redo all my schedules again...

**Comment by lmagyar** [comment]
FYI: Any scheduler update (major and minor version) in the past 2 months crushed my schedules also (I'm using HA only for 2 months). I don't have logs, don't remember the exact details of the problem, but these were the simplest, default, 3-timeslot-daily schedules for heating, without zero-length timeslots, with "heat" action for all 3 timeslots. After each update they changed and looked "weird", I manually deleted and recreated the schedules to get rid of the conversion error and it's possible lasting effects. Strange, that this is not reproducible. I'm using HASS OS. I didn't report it, because I can't reproduce it without downgrading and upgrading again, so I can't give exact details, but now I also confirm, the problem is real.

What can be a clue: usually 2 of 3 timeslots (in daily schedules) have the same action, to heat to the same temperature. This is correctly stored in the scheduler.storage file, but the identical 2 actions have only 1 entry in the entity's actions attribute. But this can be a totally misleading clue.

**Comment by nielsfaber** [comment]
I am closing this issue since I think its outdated.
Hopefully I will not break things again 😇

**Comment by Jajjaman** [comment]
Outdated or not, same problem here now.

**Comment by nielsfaber** [comment]
@Jajjaman Can you elaborate the issues you are having?
Which version of scheduler card are you using?

**Comment by avrabi19** [comment]
same issue Defective schedule entity: switch.schedule_b249a8

**Comment by foddy-foo** [comment]
Still seeing issues with "Defective schedule Entity".
Using version v3.3.8 of the scheduler-component.
The yellow entity is not clickable. Tried rebooting.

If there is any documented way of deleting such defective entities could you direct me to that.
