### ISSUE TITLE
Not specifying some options removes UI editor for that tab

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#3]
If you leave out an option, the UI editor stops working, and you have to select Raw config editor from the upper-right menu.

**Comment by KTibow** [comment]
This has been partially fixed. If any other kind of error occurs, this still happens.

**Comment by nielsfaber** [comment]
I am closing this issue, assuming it is fixed. Re-open if this is not the case.

**Comment by KTibow** [comment]
Pretty much. If any other kind of exception occurs, it still happens, but it's that way with all other cards as well. And I haven't seen an exception for >1 week.
