### ISSUE TITLE
Error because Scheduler Card sets HVAC-mode on Popp Thermostat Valve

### ISSUE THREAD

**Issue by bikeymouse** [nielsfaber/scheduler-card#350]
I reported this as well in a home-assistant/core GitHub issue about Z-Wave (see [@28834](https://github.com/home-assistant/core/issues/28834#issuecomment-803571452)), but think it is actually a Scheduler-Card bug:

Using: Core-2021.3.4 with ZWaveJS2MQTT integration,
and Scheduler Card version: 2.05:

I'm getting HVAC-related errors using my Popp "POPE010101" (= Danfoss LC-13) thermostat with the Scheduler Card. I'm setting the temperature-setpoint in a schedule, which functionally works, except I also get errors in the log file:

```
Error executing service: <ServiceCall climate.set_hvac_mode (c:f1bcab1ef24bbe11b6f1639863e91e06): hvac_mode=heat, entity_id=['climate.thermostat_sleepingroom']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1504, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/climate.py", line 404, in async_set_hvac_mode
    raise ValueError(
ValueError: Thermostat climate.thermostat_sleepingroom does not support setting a mode
```
So it seems although the thermostat is having a "HVAC mode", apparently it can not be set. It is aways "heat", so the scheduler probably should try to set it, and only change the "temperature" parameter.
```
hvac_modes: heat
min_temp: 7
max_temp: 35
preset_modes: 
current_temperature: 18.9
temperature: 20
preset_mode: none
friendly_name: Thermostat Sleeping Room
supported_features: 17
```

**Comment by nielsfaber** [comment]
This part of HA is a bit of a mystery to me..
I'd say that any climate with only 1 `hvac_mode` might as well have no `hvac_modes`.
And then, there's also a [hvac_mode](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-action) off. 
I'd say that any climate device should allow to be turned off (rather than setting it to low temperature).
My view on the matter is that this is a poor implementation of the ZWave device driver.

Anyway, I could add some logic to the card that will not try to set it to hvac_mode=heat if that's the only mode.
It should solve things for you.
In the meantime you could ignore the log error (it's pretty harmless).

**Comment by bikeymouse** [comment]
Thanks for your quick response. 
Using hvac_mode in this case is indeed a bid strange, as it is just physically a simple radiator valve, which in real-life you can only set to a target temperature. 

You can not actually turn it on. Or turn it off. Just set it to a very low/high temperature, not much more that a ZWave-driver can make from it without suggesting something that is not actually true.

Very nice if you can solve this for me and probably others, that helps to get the log nice and clean ;-)

And thanks for creating such a nice piece of functionality that should be part of the core of any home automation system!

**Comment by nielsfaber** [comment]
This should be solved with https://github.com/nielsfaber/scheduler-card/commit/fe98116e3ccf45f091e1e524c98676d78479a43a.
It will be in the upcoming release.

**Comment by nielsfaber** [comment]
V2.1.0 is released with this fix.
Please confirm whether the issue is solved after updating.

**Comment by bikeymouse** [comment]
Nope, still the same error. 

Even worse, initially the update left me with an error in the front-end that the custom scheduler-card could not be found. 
Did a reinstall but that made no difference.
When I looked at /config/www/community/schedular-card is noticed that there was only a scheduler-card.zip
Once I extracted that manually it started working again, like before.

P.s. I installed everything using HACS, however I also updated that to 1.12.3 this evening. 
Perhaps that has something  to do with it?

**Comment by bikeymouse** [comment]
For completeness, this is (the same) error:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1496, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/climate.py", line 427, in async_set_hvac_mode
    raise ValueError(
ValueError: Thermostat climate.thermostat_bedroom does not support setting a mode
```
<img width="429" alt="scheduler_card" src="https://user-images.githubusercontent.com/34967010/116664454-c75fce80-a998-11eb-96c6-3c7e30aa9cbf.png">

**Comment by nielsfaber** [comment]
Did you re-create the schedule after updating?
This is needed because updates to the cards will not affect previously created schedules.

**Comment by bikeymouse** [comment]
Didn't know that I should. So I removed the old schedules and tried to add a new one.
Unfortunately I now have another issue: I can not set the target temperature: if I click on the "Set Temperature" button there is no pop-up or box to actually set it at the proper level. 
So in the schedule it just says "set temperature" without degrees:
<img width="505" alt="set-temp" src="https://user-images.githubusercontent.com/34967010/116668306-8c13ce80-a99d-11eb-9ab3-391ea25d9e83.png">

**Comment by bikeymouse** [comment]
Update: I have tested this now with V2.1.1 and I can now set the temperature again. 

However, back to the initial issue: if I use the "set temperature" option, I still get an error in the log  ;-(

( I have deleted the old schedules and created new ones. Tried several times, also with different settings).

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1496, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/climate.py", line 427, in async_set_hvac_mode
    raise ValueError(
ValueError: Thermostat climate.thermostat_bedroom does not support setting a mode
```


Furthermore: I now see that I now also haven an option "Turn off" (missed that earlier, but is actually in the screenshot above), which is not applicable for a Radiator Valve. It only supports setting a temperature. 

I checked what happens if I use this, but it seems like this is not actually being executed, as I don't get any errors in the log  - and of course no state changes - from that (which I do get if I call the climate.turn_on or climate_turn_off service via the Developer-tools).  So not a big deal, but cosmetically.


So it seems this issue is not solved yet (look like nothing changed, actually).

For completeness, again the properties of the Radiator Valve that show that it only supports "heat":
```
hvac_modes:
  - heat
min_temp: 7
max_temp: 35
current_temperature: 19.6
temperature: 19
friendly_name: Thermostat Bedroom
supported_features: 1
```

Hope you have enough info to find how to fix it. If you need more info or something to test, please let me know!

**Comment by nielsfaber** [comment]
I think it should be fixed in the latest release.
Could you please test it?
You will need to create a new schedule (or edit an existing one) for the changes to have effect.

**Comment by bikeymouse** [comment]
Thanks for the update!

Just upgraded, removed the old schedules and create new ones. 
Unfortunately still the same error:

```
Logger: homeassistant.core
Source: components/zwave_js/climate.py:464 
First occurred: 1:13:13 (2 occurrences) 
Last logged: 1:13:13
Error executing service: <ServiceCall climate.set_hvac_mode (c:c8399cd0c8d769254c0fca8972efe675): hvac_mode=heat, entity_id=['climate.thermostat_bedroom']>
Error executing service: <ServiceCall climate.set_hvac_mode (c:fceda4951da8a7b00cec6634e9635a11): hvac_mode=heat, entity_id=['climate.thermostat_room']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1497, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/climate.py", line 464, in async_set_hvac_mode
    raise ValueError(
ValueError: Thermostat climate.thermostat_bedroom does not support setting a mode
```

**Comment by nielsfaber** [comment]
I would expect that the “heat” action does not show up in the card, but only a “set temperature”.
From the logs you sent it appears this is not the case?

**Comment by bikeymouse** [comment]
That is correct, I had to select the heat selector first to be able to set the temperature.

**Comment by nielsfaber** [comment]
>That is correct, I had to select the heat selector first to be able to set the temperature.

That should not be the case.
Could you double check the version you are running (in the browser log)?

I made a test for your entity as described in your post https://github.com/nielsfaber/scheduler-card/issues/350#issue-837611872:

![image](https://user-images.githubusercontent.com/16861605/118305954-fe7dc600-b4e8-11eb-8159-e8811ae1fa62.png)

It should show up as "set temperature" (or a translation):

![image](https://user-images.githubusercontent.com/16861605/118306087-2f5dfb00-b4e9-11eb-889b-4f5d6abef89b.png)

![image](https://user-images.githubusercontent.com/16861605/118306112-3ab12680-b4e9-11eb-99a7-fd4c7b42a97b.png)

In the schedule entity you should see that it only sets the temperature, not the hvac_mode:
![image](https://user-images.githubusercontent.com/16861605/118306150-4ac90600-b4e9-11eb-92bd-5bc37fd9406b.png)

**Comment by bikeymouse** [comment]
I'm not sure why, (could it be a cache thing?) and I feel a bit stupid, but now I tried again and it works! 
Exactly like you describe, and no more errors in the log, yeah! 
So sorry for this last mix-up, and big kudos for fixing this.
Keep up the good work! I'm closing this issue 👍
