### ISSUE TITLE
Condition: can't use 0 value as threshold

### ISSUE THREAD

**Issue by haseat** [nielsfaber/scheduler-card#487]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.0

### Component Version

v3.2.4

### Bug description

I wanted to make a condition for an input_number with "value above 0". Unfortunately, the Save button is greyed out when the value is 0 (works fine with values greater than 0).

![image](https://user-images.githubusercontent.com/61622258/145663170-f65da714-7e1a-495e-aebf-7544735d48dd.png)
![image](https://user-images.githubusercontent.com/61622258/145663216-99bd2a82-1309-4172-a7db-cc11a5c03d11.png)

I noticed a closed ticket with the same problem and tried the suggested solution, but it does not work for me:

```
type: custom:scheduler-card
title: Heating Schedules Bathroom
time_step: 15
include:
  - binary_sensor
  - climate
  - group
  - input_boolean
  - input_number
  - light
tags:
  - Heating Bathroom
display_options:
  primary_info: name
  secondary_info: '{relative-time}: {action}'
  icon: entity
discover_existing: false
customize:
  input_number.activities_bathroom_boost_heating_counter:
    states:
      min: 0
      max: 100
      step: 1
```

### Steps to reproduce

Add an input_number as an condition and try "value above 0".

**Comment by haseat** [comment]
Is there any more info you would need to have a look at this? Thanks!

**Comment by nielsfaber** [comment]
I'm sorry for ignoring your report.
I thought this issue was addressed before, but apparently not.
I found the cause of the issue and fixed it: https://github.com/nielsfaber/scheduler-card/commit/1f299d3eb20786981dfeda4ab625effbc2b61999.

Now it should work for negative values:
![image](https://user-images.githubusercontent.com/16861605/150664635-22bca9e1-0038-447e-a51f-77d397fc7e12.png)

As well as zero value:
![image](https://user-images.githubusercontent.com/16861605/150664655-2aa69001-f047-4257-89de-ea9524da1a9d.png)

This change will be part of the next release.

**Comment by nielsfaber** [comment]
Release v2.3.1 is out which contains this fix.
 Please test it and close the issue if the problem is fixed, otherwise let me know.

**Comment by haseat** [comment]
Hi,

unfortunately it's still not working:

https://watch.screencastify.com/v/LUpIc25jLVXgJVeXGTEj

![image](https://user-images.githubusercontent.com/61622258/151104845-61081250-324b-48d4-8cd9-9a279fa4186d.png)

If there's anything to pinpoint the problem, please let me know.

**Comment by nielsfaber** [comment]
Thanks for the video, I feel stupid now 😅 
I only focused on having the 'save' button clickable, I thought that was the only issue preventing you from adding the condition (as you can see it does become blue now, so there is some improvement). 
I didn't realise that there was a second check in the code (which I didn't change), as a result nothing happens when you click save.
Anyway, that's fixed now, also your video shows that you are required to move the slider before the save button becomes clickable, I addressed that too.
Will have to make another release before you can use it though, I'll keep you updated.

**Comment by nielsfaber** [comment]
This should be fixed in release v2.3.2. 
Please update and test if the problem is solved now, you can close the issue if so.

**Comment by haseat** [comment]
This works perfectly fine now. Thanks!
