### ISSUE TITLE
Scheduler Card not working after updating to 2022.6.0

### ISSUE THREAD

**Issue by zuchie-star** [nielsfaber/scheduler-card#560]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.4

### Component Version

v3.2.9

### Bug description

Scheduler card stopped working after updating to 2022.6.0. I tried uninstalling both the card & the component and then re-installed, however its the same issue.

From the log;
2022-06-02 10:08:08 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for scheduler using this method at custom_components/scheduler/__init__.py, line 47: device_registry = await dr.async_get_registry(hass)

![image](https://user-images.githubusercontent.com/79965154/171531851-391e0545-222c-41bc-9b98-143a4ebd5fd8.png)

All my schedules seem to be running fine though.

### Steps to reproduce

Upgraded to 2022.6.0

**Comment by nielsfaber** [comment]
This should be fixed by updating scheduler component to 3.2.10.

**Comment by stomko11** [comment]
I updated the scheduler component to 3.2.10 and I still get the same error when adding the scheduler card.

**Comment by zuchie-star** [comment]
Same, still not working after updating to 3.2.10

![image](https://user-images.githubusercontent.com/79965154/171582828-2d53ce4e-2cd0-45e6-9146-6d49708b0abf.png)

**Comment by nielsfaber** [comment]
Anything shown in the HA logs?
Any other clues which could help me reproduce the issue? For me all shows up fine.

**Comment by stomko11** [comment]
The only thing I see in HA log after enabling debug is:
```
logger:
  default: info
```

```
2022-06-02 10:12:49 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140340202850864] Received unknown command: scheduler
2022-06-02 10:12:49 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140340202850864] Received unknown command: scheduler
2022-06-02 10:12:49 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140340202850864] Received unknown command: scheduler_updated
2022-06-02 10:12:51 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140340202850864] Received unknown command: scheduler
2022-06-02 10:12:51 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140340202850864] Received unknown command: scheduler_updated
```

**Comment by nielsfaber** [comment]
@stomko11 Is the scheduler integration set up correctly?
Do you see this entry under settings -> devices:
<img src="https://user-images.githubusercontent.com/16861605/171586303-20636061-21ab-4c82-987a-5f7d035e3abe.png" width="50%" height="50%">

**Comment by stomko11** [comment]
@nielsfaber actually, I did not. I added it and now my card is OK.

**Comment by zuchie-star** [comment]
Ok so i just got home from holidays, i uninistalled the scheduler integration + the card and then re-installed and everything is working fine now. Thanks
