### ISSUE TITLE
Cannot set scheduler time

### ISSUE THREAD

**Issue by jkremlacek** [nielsfaber/scheduler-card#991]
### Checklist

- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v4.0.5

### Component Version

v3.3.8

### Bug description

Setting any time in schedule creates error in browser and home assistant log and actual set time will be always midnight next day.

### Steps to reproduce

Set any time into scheduler card and attempt to save.

Error occurs on Windows with Firefox browser and iOS with Safari browser.

### Additional info

Browser log: 

```
Uncaught TypeError: can't access property "stop", Object.assign(...)[(t - 1)] is undefined
    Ca http://ha.home:8123/hacsfiles/scheduler-card/scheduler-card.js?hacstag=286270157405:1286
    _startTimeChanged http://ha.home:8123/hacsfiles/scheduler-card/scheduler-card.js?hacstag=286270157405:2152
    handleEvent http://ha.home:8123/hacsfiles/scheduler-card/scheduler-card.js?hacstag=286270157405:17
    Ms http://ha.home:8123/hacsfiles/scheduler-card/scheduler-card.js?hacstag=286270157405:59
    _valueChanged http://ha.home:8123/hacsfiles/scheduler-card/scheduler-card.js?hacstag=286270157405:1600
    _addTimeOffset http://ha.home:8123/hacsfiles/scheduler-card/scheduler-card.js?hacstag=286270157405:1600
    render http://ha.home:8123/hacsfiles/scheduler-card/scheduler-card.js?hacstag=286270157405:1489
    handleEvent http://ha.home:8123/hacsfiles/scheduler-card/scheduler-card.js?hacstag=286270157405:17
```

Place in code:

<img width="1250" height="35" alt="Image" src="https://github.com/user-attachments/assets/981f6e6e-7c25-4044-8825-75ceaf1b8c62" />

```javascript
...
ns(
  (
    e = Object.assign(e, {
      [
        t
      ]: Object.assign(Object.assign({
      }, e[t]), {
        start: qe(n)
      })
    })
  ) [t - 1].stop                 // <<< here error occurs
) ? e = Object.assign(
...
```

HASS log:

```
2025-09-29 00:11:55.560 ERROR (MainThread) [frontend.js.modern.202509035] Uncaught error from Firefox 143.0 on Windows 10
TypeError: can't access property "stop", Object.assign(...)[(t - 1)] is undefined
Ca (/hacsfiles/scheduler-card/scheduler-card.js:1286:2424)
_startTimeChanged (/hacsfiles/scheduler-card/scheduler-card.js:2152:3520)
handleEvent (/hacsfiles/scheduler-card/scheduler-card.js:17:7386)
Ms (/hacsfiles/scheduler-card/scheduler-card.js:59:150336)
_valueChanged (/hacsfiles/scheduler-card/scheduler-card.js:1600:1245)
_addTimeOffset (/hacsfiles/scheduler-card/scheduler-card.js:1600:1148)
render/< (/hacsfiles/scheduler-card/scheduler-card.js:1489:33)
handleEvent (/hacsfiles/scheduler-card/scheduler-card.js:17:7386)
2025-09-29 00:12:32.963 ERROR (MainThread) [frontend.js.modern.202509035] Uncaught error from WebKit 605.1.15 on iOS 18.6
TypeError: undefined is not an object (evaluating '(e=Object.assign(e,{[t]:Object.assign(Object.assign({},e[t]),{start:qe(n)})}))[t-1].stop')
Ca (/hacsfiles/scheduler-card/scheduler-card.js:1286:2497)
_startTimeChanged (/hacsfiles/scheduler-card/scheduler-card.js:2152:3520)
handleEvent (/hacsfiles/scheduler-card/scheduler-card.js:17:7390)
dispatchEvent ([native code]::)
Ms (/hacsfiles/scheduler-card/scheduler-card.js:59:150349)
_valueChanged (/hacsfiles/scheduler-card/scheduler-card.js:1600:1245)
_addTimeOffset (/hacsfiles/scheduler-card/scheduler-card.js:1600:1161)
handleEvent (/hacsfiles/scheduler-card/scheduler-card.js:17:7390)
```

**Comment by jkremlacek** [comment]
Another observation after noticing that different schedule works - bug occurs when i use arrows to cross hours over midnight (22 -> 23 -> 0 -> 1) and then save the change

**Comment by 02curls** [comment]
I experience exactly the same behaviour, perhaps issue related to https://github.com/nielsfaber/scheduler-card/issues/986#issuecomment-3332345042 ?

**Comment by Lemming16** [comment]
I'm seeing the same problem.
If schedule is once set to 00:00, I can't change it again. Only option is to delete the schedule and create a new.

**Comment by zigfred** [comment]
+1 in mobile app

**Comment by jointerCZ** [comment]
I am experiencing the same issue, together with the item duplication. https://github.com/nielsfaber/scheduler-card/issues/999 But I feel like this is more important.

**Comment by nielsfaber** [comment]
Unfortunately I am unable to reproduce this issue.
I would like to ask for someone to help me identifying the issue by providing the following:
1. Install debug version of scheduler-card and provide the full error log
2. create a screen video to demonstrate how/when the issue occurs

For installing the debug version, please use the attached file with the link below and unzip it.
This file should be used to replace the original `scheduler-card.js` file in the `/www/` subfolder of your HA installation folder.
If you use HACS, there might be a `scheduler-card.js.gz` file in the same folder as `scheduler-card.js`, it should be deleted or renamed such that it won't be loaded. Note that HACS stores its files in `/www/community`.

After replacing the file, you will need to clear your browser cache or perform a perform refresh to load the updated version.
To verify that thi went well, follow [instructions here](https://github.com/nielsfaber/scheduler-card?tab=readme-ov-file#checking-card-version) to check your card version. This should be displaying **v4.0.7b**, so with an additional letter **b** at the end.

With the debug version installed, please share the full error message in the browser console logs.

Thanks in advance for helping out 👍 

[scheduler-card.js.zip](https://github.com/user-attachments/files/22876570/scheduler-card.js.zip)

**Comment by jkremlacek** [comment]
## Error log using debug version:

[errorlog.txt](https://github.com/user-attachments/files/22878232/errorlog.txt)

## Screenshot:

<img width="1097" height="448" alt="Image" src="https://github.com/user-attachments/assets/b276d7ea-b09a-481b-b334-517d1a7741fe" />

## Video:

https://github.com/user-attachments/assets/34f84495-fbc0-4654-8f65-fe18389fada7

**Comment by nielsfaber** [comment]
I created a fix for this issue (https://github.com/nielsfaber/scheduler-card/commit/5a12033541e74f2505e392ea47efd976a8d2af59), I will let you know when this is released.

**Comment by pckeller29** [comment]
Scheduler Card 4.0.8
Scheduler Component 3.3.8
HAOS 2025.10.4
Still having the same issue. I believe I cleared my cache correctly.

**Comment by jkremlacek** [comment]
Same for me, I installed 4.0.8 - which replaced the debug version of the code - and bug is still present

**Comment by 02curls** [comment]
Still having the same issue too

**Comment by nielsfaber** [comment]
Version v4.0.8 should address the issue that is shown in the video here https://github.com/nielsfaber/scheduler-card/issues/991#issuecomment-3396121457.
@jkremlacek can you confirm this is solved in the new version?

Is there any problem left with the new version? If so, can someone provide the relevant information as requested here: https://github.com/nielsfaber/scheduler-card/issues/991#issuecomment-3395821175

**Comment by jkremlacek** [comment]
I already replied 2 posts above that it was not fixed for me. For clarity, here is recording of the bug in 4.0.8:

https://github.com/user-attachments/assets/9e1dd929-ea2d-4760-ba88-1a2281ed642e

**Comment by pckeller29** [comment]
Here is a video

https://github.com/user-attachments/assets/e73c88e8-54d4-4115-99d2-d22eabf7a2ba

**Comment by pckeller29** [comment]
And this is the console log I get after passing by 00:00 and saving the schedue

<img width="1913" height="241" alt="Image" src="https://github.com/user-attachments/assets/a16a0829-f1f9-4c61-b064-c083e62a6e1e" />

**Comment by pckeller29** [comment]
And the "Know more" link at the bottom of the previous log console:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type
Maybe it can help ;-)

**Comment by nielsfaber** [comment]
I made a second attempt for a (potential) fix, I would appreciate if someone could test this out before making a new release.

For installing the updated version, please use the attached file with the link below and unzip it.
This file should be used to replace the original `scheduler-card.js` file in the `/www/` subfolder of your HA installation folder.
If you use HACS, there might be a `scheduler-card.js.gz` file in the same folder as `scheduler-card.js`, it should be deleted or renamed such that it won't be loaded. Note that HACS stores its files in `/www/community`.

After replacing the file, you will need to clear your browser cache or perform a perform refresh to load the updated version.
To verify that this went well, follow [instructions here](https://github.com/nielsfaber/scheduler-card?tab=readme-ov-file#checking-card-version) to check your card version. This should be displaying **v4.0.8b**, so with an additional letter **b** at the end.

Thanks in advance for helping out 👍 

[scheduler-card.js.zip](https://github.com/user-attachments/files/23540316/scheduler-card.js.zip)

**Comment by jkremlacek** [comment]
Using provided version `v4.0.8b` bug no longer occurs to me. Great!

**Comment by pckeller29** [comment]
Good job. V4.0.8b works for me as well

**Comment by nielsfaber** [comment]
I just released v4.0.9 of scheduler-card, which includes the fix that has been discussed here.
I am assuming the new version will fix the problems for all users, therefor I will close the issue.
If you still experience this problem after updating, please add a comment.
